### ISSUE TITLE
Hide internal technologies.

### ISSUE THREAD

**Issue by Aidiakapi** [Aidiakapi/qol_research#1]
0.16.23 broke the trick I used to hide the internal technologies.

I've submitted a modding interface request in order to hide them again: https://forums.factorio.com/viewtopic.php?t=57876

**Comment by Aidiakapi** [comment]
Modding interface request will be fulfilled for 0.17.

**Comment by AbbyNode** [comment]
With [Improved Research Queue](https://mods.factorio.com/mod/sonaxaton-research-queue) enabled, the internal technologies show up in the chat notifications.

![factorio_8WaGGIYeyS](https://user-images.githubusercontent.com/28557231/128057372-1266f0f3-ce70-4613-9dee-d0d8f7424a1f.png)

**Comment by Aidiakapi** [comment]
@AbbyNode Correct, someone reported this (see #5). This is not something I can fix on my side, but instead has to be fixed in their mod. Sadly they didn't respond to it :/.
