### ISSUE TITLE
Mod not found

### ISSUE THREAD

**Issue by BigBrian3351** [Aidiakapi/qol_research#10]
When I downloaded the mod and inserted it into the mod folder the mod didn't show up on factorio.

**Comment by Aidiakapi** [comment]
Assuming you downloaded from GitHub, the most likely reason is that you didn't package the mod correctly.
The src directory needs to be renamed to the full mod name, then packaged into zip file with that same name.

You can save yourself the trouble by just downloading it from the mod portal, as that's the official distribution channel.

**Comment by cyhno4o** [comment]
> Assuming you downloaded from GitHub, the most likely reason is that you didn't package the mod correctly. The src directory needs to be renamed to the full mod name, then packaged into zip file with that same name.
> 
> You can save yourself the trouble by just downloading it from the mod portal, as that's the official distribution channel.

I don't know why but I can't download the mod from the portal. So the file was named "qol_research-master" or something like that and I renamed it to "qol_research_3.3.3" just to see if it would work. Certainly it doesn't. What is the correct file name? Really wanna use your mod
