### ISSUE TITLE
small incompatibility with Improved Research Queue

### ISSUE THREAD

**Issue by rachelf42** [Aidiakapi/qol_research#11]
**the problem:** internal technology is visible with IRQ's notifications
![image](https://user-images.githubusercontent.com/59665717/121995354-a510ed00-cd5b-11eb-8f87-74b79ada9b0b.png)
**how to reproduce:** install [IRQ](https://mods.factorio.com/mod/sonaxaton-research-queue), open its per-player settings, ensure "Research completion notifications" is checked, then load any map and research any QoL tech

i dont think this is a huge deal personally, and if i hadn't noticed that the tooltip asks me to file a bug report i probably wouldn't have, but since i did notice it i figured i should probably at least make sure you're aware of it
thanks for the great mod btw!

**Comment by Aidiakapi** [comment]
Hey, thanks for letting me know!

Seems like IRQ is not respecting the "hidden" flag on the technology, I'll see if I can take it up with the author there :)
