### ISSUE TITLE
Make math functions usable in cost formula

### ISSUE THREAD

**Issue by MadProbe** [Aidiakapi/qol_research#12]
I want to use the `log()` and `sqrt()` functions to make the cost more forgiving when researching each level of qol research but currently I don't have a clue how to do this with your mod or atleast something like that now

**Comment by Aidiakapi** [comment]
The cost formulas are a feature of the base game, not something controlled by the mod:
https://wiki.factorio.com/Prototype/Technology#unit

As such, I don't think you'll be able to use `log`, but you can do exponentiation, and as such, you should be able to do `sqrt`: `x^0.5`.
