### ISSUE TITLE
[Suggestion] `Nullius` compatibility

### ISSUE THREAD

**Issue by ExterminatorX99** [Aidiakapi/qol_research#13]
Would you consider adding compatibility with the [Nullius](https://mods.factorio.com/mod/nullius) mod?

It is a full overhaul mod that makes it so that other mods need explicit compatibility for their content to be available.
As such, the qol techs added by your mod are unavailable.
I'm don't know how much work it is to add compatibility, but Nullius' FAQ page has a section explaining how to add compatibility with it.

**Comment by Aidiakapi** [comment]
Hey! Sorry it's taken me a while to get back to this.
I've added some basic compatibility with the mod, and uploaded a new version 3.3.2. It now loads fine, the researches show up, and researching some things seems to work.

If the default configuration/balancing doesn't play nicely with the mod, feel free to suggest an alternative configuration. Information on how to do that can be found in the [FAQ](https://mods.factorio.com/mod/qol_research/faq).

**Comment by ExterminatorX99** [comment]
Thanks a bunch

**Comment by solarshado** [comment]
This appears to be broken now? The researches show up, but even with "Enable modpack config override" checked require the vanilla science packs, which Nullius disables.

QoL Research version: 3.3.3  
Nullius version: 1.6.6
