### ISSUE TITLE
Bug: Seeing "Quality of Life research internal technology" ingame

### ISSUE THREAD

**Issue by jbfredheim** [Aidiakapi/qol_research#15]
Providing you with a little bug reported as requested in the tooltip of the research.
![image](https://github.com/Aidiakapi/qol_research/assets/42445077/a1d9f586-75bd-46c6-aeee-7ff8f22204db)

Modlist;
```
{
  AfraidOfTheDark = "1.1.1",
  AutoDeconstruct = "0.3.8",
  BlueprintLab_Blu3wolf = "1.0.4",
  Bottleneck = "0.11.7",
  ["Chunk-Aligned"] = "1.1.69",
  CleanFloor = "1.1.0",
  EvoGUI = "0.4.601",
  GhostOnWater = "0.12.1",
  LandfillEverything = "1.1.2",
  LogisticRequestManager = "1.1.31",
  Milestones = "1.3.20",
  ModuleInserter = "5.2.4",
  ["Power Armor MK3"] = "0.4.2",
  RateCalculator = "3.2.3",
  RecipeBook = "3.5.6",
  SE_Cheaper_Floors = "1.0.0",
  SE_smooth_ship_walls = "1.0.0",
  SantasNixieTubeDisplay = "0.1.12",
  ["Squeak Through"] = "1.8.2",
  TimeTools = "2.1.44",
  UltimateResearchQueue = "1.0.12",
  VehicleSnap = "1.18.5",
  Waterfill_v17 = "1.1.0",
  YARM = "0.10.13",
  ["aai-containers"] = "0.2.11",
  ["aai-industry"] = "0.5.20",
  ["aai-loaders"] = "0.1.4",
  ["aai-signal-transmission"] = "0.4.8",
  ["aai-vehicles-flame-tumbler"] = "0.6.1",
  ["aai-vehicles-ironclad"] = "0.6.8",
  ["alien-biomes"] = "0.6.8",
  ["alien-biomes-hr-terrain"] = "0.6.1",
  base = "1.1.87",
  ["bullet-trails"] = "0.6.2",
  ["calculator-ui"] = "1.1.1",
  ["combat-mechanics-overhaul"] = "0.6.24",
  ["creative-mod"] = "1.8.1",
  cybersyn = "1.2.16",
  ["equipment-gantry"] = "0.1.5",
  ["even-distribution"] = "1.0.10",
  ["far-reach"] = "1.1.3",
  fast_trans = "1.1.3",
  flib = "0.12.9",
  ["grappling-gun"] = "0.3.3",
  helmod = "0.12.19",
  informatron = "0.3.4",
  jetpack = "0.3.13",
  ["power-grid-comb"] = "1.1.0",
  pushbutton = "1.1.1",
  qol_research = "3.3.3",
  robot_attrition = "0.5.15",
  ["rocket-log"] = "1.1.11",
  ["shield-projector"] = "0.1.6",
  simhelper = "1.1.4",
  ["space-exploration"] = "0.6.113",
  ["space-exploration-graphics"] = "0.6.15",
  ["space-exploration-graphics-2"] = "0.6.1",
  ["space-exploration-graphics-3"] = "0.6.2",
  ["space-exploration-graphics-4"] = "0.6.2",
  ["space-exploration-graphics-5"] = "0.6.1",
  ["space-exploration-menu-simulations"] = "0.6.8",
  ["space-exploration-postprocess"] = "0.6.26",
  stdlib = "1.4.8",
  textplates = "0.6.10"
}
```

**Comment by jbfredheim** [comment]
Update;
<img width="332" alt="image" src="https://github.com/Aidiakapi/qol_research/assets/42445077/0934e5a2-867c-476f-9d4f-daef103f4164">
Seems to be pretty consistently happening.
I'm not very familiar with the factorio api and haven't look at any of the inner workings so no suggestions i'm afraid. Best guess is the ultimate research queue or milestones mod might both be listening for research events

**Comment by Aidiakapi** [comment]
Hey, thanks for the report!

This has been reported several times already (https://github.com/Aidiakapi/qol_research/issues/1#issuecomment-892016554, https://github.com/Aidiakapi/qol_research/issues/11, https://mods.factorio.com/mod/qol_research/discussion/621a82f69cbf51b6f31e1655, https://mods.factorio.com/mod/qol_research/discussion/63f284cd5426164f1059ce8a).

It's a bug in the research queue mod, and there's not much I can do to fix it.
I've provided a patch to one of the authors on GitHub (https://github.com/dbeckwith/factorio-research-queue/issues/4), but it's been ignored.

I should probably change the wording to report it to whatever mod is showing it, instead of here.
