### ISSUE TITLE
factorio 0.17 loses mod settings

### ISSUE THREAD

**Issue by nucleargen** [Aidiakapi/qol_research#4]
Mod settings resets to defaults when changing other mods (installing/updating): i use no basic bonuses for crafting/speed/mining, but it resets to value = 1 (+100% base modifier)

Load game screen after adding another mod:
http://dl4.joxi.net/drive/2019/03/06/0003/2693/236165/65/a0ecd09a03.jpg
Current bonuses (+10 slots gained from toolbelt upgrade from base game):
http://dl3.joxi.net/drive/2019/03/06/0003/2693/236165/65/f9d8d6280d.jpg

**Comment by Aidiakapi** [comment]
To make sure I'm not misunderstanding. The applied bonuses in-game are in sync with the settings. It's the settings themselves that are getting reset, correct?

If so, mods cannot actually change setting values. So it's either my mod or a different mod changing the mod setting names, or it's a bug in the actual game.

Regardless, I'm going to look into it.
Could you perhaps send me your mods folder? (https://wetransfer.com/)
What version of 0.17 are you on?

**Comment by Aidiakapi** [comment]
I cannot reproduce the issue at all. It might have something to do with how the game actually handles runtime settings. If you change them in the main menu, and then load a savefile, they are applied sometimes, but other times they aren't.

Regardless, without a reproduction, I can't really do anything.

**Comment by nucleargen** [comment]
Catched on 0.17.4-0.17.6 versions.
Today updated to 0.17.7 and updated/installed some mods - settings remains ok.
I will notify if problem repeats.
