### ISSUE TITLE
Idea & question: forum post

### ISSUE THREAD

**Issue by SGZ-TW-TY-20** [Aidiakapi/qol_research#6]
https://forums.factorio.com/viewtopic.php?f=34&t=88764&p=510005#p510005

**Comment by Aidiakapi** [comment]
I'm not sure how that post relates to this mod. This mod explicitly doesn't affect your factory at all, it's solely quality of life improvements.

**Comment by SGZ-TW-TY-20** [comment]
Not sure how i posted this here. Sorry must have had to pages up at once and closed the wrong one

**Comment by Aidiakapi** [comment]
No problem :)
