### ISSUE TITLE
Health increase research

### ISSUE THREAD

**Issue by mecejide** [Aidiakapi/qol_research#7]
A set of technologies that increase player health would be really cool.

**Comment by Aidiakapi** [comment]
Hey there. It's a bit of a tricky situation. This mod intentionally avoids any modifications that impact the factory, or anything other than general QoL. The primary thing health would do is lower the difficulty of combat, which doesn't really fall in the quality of life category.

However, the current modifiers also break this a little bit. Movement speed can make combat a lot easier, and long reach allows you to turret creep in a much safer manner. Hell, technically seen handcrafting speed can make more "ammo/grenades" or stuff on the fly.

I think player health crosses the line, in that its almost exclusively for combat purposes. Therefore without a good argument I wouldn't feel comfortable adding this at the time.

**Comment by Frontrider** [comment]
Kind of a necro, but there is single reason to have this feature behind a toggle:
Mods like [rampant](https://mods.factorio.com/mod/Rampant) that drastically increase the difficulty of combat. In that environment, I could argue that increasing your own hp via research (aka constant production, if you can somehow push it out) makes a lot of sense, and is in the spirit of Factorio.

Again, strictly behind a toggle, disabled by default, and labeled to make the purpose blatantly obvious. A note that it is absolutely not meant to be used without other mods to balance it out.


Just providing a possible reason, your view is completely valid. In vanilla factorio combat can trivialized as soon as you unlock flamethrowers.
